// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: functions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const cosineSimilarity = `-- name: CosineSimilarity :many
SELECT
  function_id,
  function_name,
  embedding,
  js,
  embedding <=> $1 AS distance
FROM functions
ORDER BY distance ASC
LIMIT $2
`

type CosineSimilarityParams struct {
	Embedding pgvector.Vector
	Limit     int32
}

type CosineSimilarityRow struct {
	FunctionID   pgtype.UUID
	FunctionName string
	Embedding    pgvector.Vector
	Js           string
	Distance     interface{}
}

func (q *Queries) CosineSimilarity(ctx context.Context, arg CosineSimilarityParams) ([]CosineSimilarityRow, error) {
	rows, err := q.db.Query(ctx, cosineSimilarity, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CosineSimilarityRow
	for rows.Next() {
		var i CosineSimilarityRow
		if err := rows.Scan(
			&i.FunctionID,
			&i.FunctionName,
			&i.Embedding,
			&i.Js,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFunction = `-- name: CreateFunction :one
INSERT INTO functions (
  function_name,
  embedding,
  js
) VALUES (
  $1, $2, $3
)
ON CONFLICT (function_name) DO NOTHING
RETURNING function_id, function_name, embedding, js
`

type CreateFunctionParams struct {
	FunctionName string
	Embedding    pgvector.Vector
	Js           string
}

func (q *Queries) CreateFunction(ctx context.Context, arg CreateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, createFunction, arg.FunctionName, arg.Embedding, arg.Js)
	var i Function
	err := row.Scan(
		&i.FunctionID,
		&i.FunctionName,
		&i.Embedding,
		&i.Js,
	)
	return i, err
}
