// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Function struct {
	FunctionID   pgtype.UUID
	FunctionName string
	Embedding    pgvector.Vector
	Js           string
}
